'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Common
    'app.title': 'sglapp',
    'app.loading': 'Loading...',
    'app.retry': 'Retry',
    'app.error': 'An error occurred',
    'app.save': 'Save',
    'app.cancel': 'Cancel',
    'app.delete': 'Delete',
    'app.edit': 'Edit',
    'app.view': 'View',
    'app.search': 'Search',
    'app.filter': 'Filter',
    'app.filters': 'Filters',
    'app.sort': 'Sort',
    'app.actions': 'Actions',
    'app.confirm': 'Confirm',
    'app.back': 'Back',
    'app.next': 'Next',
    'app.previous': 'Previous',
    'app.refresh': 'Refresh',
    'app.showing': 'Showing',
    'app.to': 'to',
    'app.of': 'of',
    'app.results': 'results',
    'app.page': 'Page',
    'app.yes': 'Yes',
    'app.no': 'No',
    'app.rights': 'All Rights Reserved',
    'app.actionCannotBeUndone': 'This action cannot be undone.',
    'app.create': 'Create',
    'app.update': 'Update',
    'app.export': 'Export',
    'app.import': 'Import',
    'app.download': 'Download',
    'app.upload': 'Upload',
    'app.remove': 'Remove',
    'app.selectAll': 'Select All',
    'app.clearSelection': 'Clear Selection',
    'app.filterOptions': 'Filter Options',
    'app.fromDate': 'From Date',
    'app.toDate': 'To Date',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.users': 'Users',
    'nav.cards': 'Cards & Albums',
    'nav.admins': 'Admin Management',
    'nav.albums': 'Albums',
    'nav.codes': 'QR & Codes',
    'nav.banners': 'Banners',
    'nav.store': 'Store',
    'nav.sales': 'Sales',
    'nav.reports': 'Reports',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',

    // Dashboard
    'dashboard.overview': 'Dashboard Overview',
    'dashboard.subtitle': 'Monitor your admin panel performance and user statistics',
    'dashboard.totalUsers': 'Total Users',
    'dashboard.totalUsersDesc': 'Registered users',
    'dashboard.totalCards': 'Total Cards',
    'dashboard.totalCardsDesc': 'Cards in system',
    'dashboard.totalAlbums': 'Total Albums',
    'dashboard.totalAlbumsDesc': 'Albums in system',
    'dashboard.totalQrCodes': 'Total QR Codes',
    'dashboard.totalQrCodesDesc': 'Redeem code documents',
    'dashboard.totalPacks': 'Total Packs',
    'dashboard.totalPacksDesc': 'Packs in store',
    'dashboard.totalBanners': 'Total Banners',
    'dashboard.totalBannersDesc': 'Banners in system',
    'dashboard.totalSales': 'Total Sales',
    'dashboard.totalSalesDesc': 'Sum of sales prices',
    'dashboard.last7Days': 'Last 7 days',
    'dashboard.last30Days': 'Last 30 days',
    'dashboard.last90Days': 'Last 90 days',
    'dashboard.lastYear': 'Last year',
    
    // Auth
    'auth.login': 'Login',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.emailRequired': 'Email is required',
    'auth.emailInvalid': 'Please enter a valid email',
    'auth.passwordRequired': 'Password is required',
    'auth.passwordTooShort': 'Password must be at least 6 characters',
    'auth.rememberMe': 'Remember me',
    'auth.demoCredentials': 'Demo credentials',
    
    // Users
    'users.title': 'User Management',
    'users.description': 'Manage users and their details',
    'users.search': 'Search users...',
    'users.searchPlaceholder': 'Search users...',
    'users.filter': 'Filter',
    'users.username': 'Username',
    'users.email': 'Email',
    'users.points': 'Points',
    'users.status': 'Status',
    'users.registrationDate': 'Registration Date',
    'users.actions': 'Actions',
    'users.edit': 'Edit',
    'users.delete': 'Delete',
    'users.activate': 'Activate',
    'users.deactivate': 'Deactivate',
    'users.suspend': 'Suspend',
    'users.unsuspend': 'Unsuspend',
    'users.confirmDelete': 'Are you sure you want to delete this user?',
    'users.allStatuses': 'All Statuses',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.suspended': 'Suspended',
    'users.allPoints': 'All Points',
    'users.lowPoints': 'Low Points',
    'users.mediumPoints': 'Medium Points',
    'users.highPoints': 'High Points',
    'users.previous': 'Previous',
    'users.next': 'Next',
    'users.showing': 'Showing',
    'users.to': 'to',
    'users.of': 'of',
    'users.results': 'results',
    'users.userDetails': 'User Details',
    'users.profileInformation': 'Profile Information',
    'users.activity': 'User Activity',
    'users.activityPlaceholder': 'User activity data will be displayed here',
    'users.collectedCards': 'Collected Cards',
    'users.collectedCardsPlaceholder': 'User collected cards will be displayed here',
    'users.add': 'Add User',
    'users.addInfluencer': 'Add Influencer',
    'users.cardsOwned': 'Cards Owned',
    'users.cardTypesAndCounts': 'Card Types & Counts',
    'users.addNewUser': 'Add New User',
    'users.addNewInfluencer': 'Add New Influencer',
    'users.isInfluencer': 'Is Influencer',
    'users.firstName': 'First Name',
    'users.lastName': 'Last Name',
    'users.enterFirstName': 'Enter first name',
    'users.enterLastName': 'Enter last name',
    'users.enterEmail': 'Enter email address',
    'users.enterPassword': 'Enter password',
    'users.dateOfBirth': 'Date of Birth',
    'users.country': 'Country',
    'users.state': 'State',
    'users.city': 'City',
    'users.gender': 'Gender',
    'users.language': 'Language',
    'users.selectCountry': 'Select Country',
    'users.selectGender': 'Select Gender',
    'users.selectLanguage': 'Select Language',
    'users.male': 'Male',
    'users.female': 'Female',
    'users.other': 'Other',
    'users.english': 'English',
    'users.spanish': 'Spanish',
    'users.passwordMinLength': 'Password must be at least 8 characters long',
    'users.addUser': 'Add User',
    'users.deleteConfirmTitle': 'Confirm Delete',
    'users.deleteSuccess': 'User deleted successfully!',
    'users.deleteFailed': 'Failed to delete user',
    'users.deleteError': 'An error occurred while deleting the user',

    // Sales
    'sales.title': 'Sales Report',
    'sales.subtitle': 'Manage and view all sales transactions',
    'sales.exportExcel': 'Export Excel',
    'sales.exportCSV': 'Export CSV',
    'sales.deleteSelected': 'Delete Selected',
    'sales.pinUnpin': 'Pin/Unpin',
    'sales.ariaDeleteSelected': 'Delete selected',
    'sales.ariaPinUnpinSelected': 'Pin or unpin selected',
    'sales.searchPlaceholder': 'Search by Sale ID or Username...',
    'sales.filters': 'Filters',
    'sales.referrerName': 'Referrer Name',
    'sales.fromDate': 'From Date',
    'sales.toDate': 'To Date',
    'sales.minAmount': 'Min Amount',
    'sales.maxAmount': 'Max Amount',
    'sales.minAmountPlaceholder': '0.00',
    'sales.maxAmountPlaceholder': '999.99',
    'sales.resetFilters': 'Reset Filters',
    'sales.filterSummary.referrer': 'Referrer:',
    'sales.filterSummary.from': 'From:',
    'sales.filterSummary.to': 'To:',
    'sales.filtering': 'Filtering...',
    'sales.loading': 'Loading sales...',
    'sales.noResults': 'No sales found for current filters.',
    'sales.resolving': 'Resolving…',
    'sales.allReferrers': 'All Referrers',
    'sales.selectAllOnPage': 'Select all on page',
    'sales.selectSale': 'Select sale {id}',
    'sales.pinned': 'Pinned',
    'sales.noReferrer': 'No Referrer',
    'sales.unknownUser': 'Unknown user',
    'sales.header.sr': 'Sr#',
    'sales.header.saleId': 'Sale ID',
    'sales.header.username': 'Username',
    'sales.header.refererName': 'Referrer Name',
    'sales.header.createdAt': 'Created At',
    'sales.header.price': 'Price',
    'sales.realtimeUnavailable': 'Real-time updates unavailable. Showing latest snapshot.',
    'sales.unableToLoad': 'Unable to load sales. Check your network or authentication.',
    'sales.initRealtimeFailed': 'Failed to initialize real-time sales feed.',
    'sales.refreshFailed': 'Refresh failed. Please check your connection.',
    'sales.confirmDeleteSelected': 'Delete {count} selected sale(s)? This cannot be undone.',
    'sales.deleteResultMixed': 'Deleted {success} sale(s), {failed} failed.',
    'sales.deleteResult': 'Deleted {success} sale(s).',
    'sales.pinToggleResult': 'Pinned {pinned}, unpinned {unpinned}.',
    'sales.sheetName': 'Sales Report',
    'auth.signInRequired': 'Sign in may be required.',
    
    // Admins
    'admins.title': 'Admin Management',
    'admins.search': 'Search admins...',
    'admins.filter': 'Filter',
    'admins.username': 'Username',
    'admins.email': 'Email',
    'admins.lastLogin': 'Last Login',
    'admins.createdDate': 'Created Date',
    'admins.permissions': 'Permissions',
    'admins.actions': 'Actions',
    'admins.edit': 'Edit',
    'admins.delete': 'Delete',
    'admins.view': 'View',
    'admins.confirmDelete': 'Are you sure you want to delete this admin?',
    'admins.previous': 'Previous',
    'admins.next': 'Next',
    'admins.showing': 'Showing',
    'admins.to': 'to',
    'admins.of': 'of',
    'admins.results': 'results',
    'admins.loading': 'Loading admins...',
    'admins.loadingFor': 'Loading admins for',
    'admins.adminDetails': 'Admin Details',
    'admins.profileInformation': 'Profile Information',
    'admins.permissionsList': 'Permissions List',
    'admins.addNew': 'Add New Admin',
    'admins.editAdmin': 'Edit Admin',
    'admins.password': 'Password',
    'admins.confirmPassword': 'Confirm Password',
    'admins.selectPermissions': 'Select Permissions',
    'admins.allPermissions': 'All Permissions',
    'admins.enterUsername': 'Enter username',
    'admins.enterEmail': 'Enter email address',
    'admins.users': 'Users',
    'admins.cards': 'Cards',
    'admins.albums': 'Albums',
    'admins.codes': 'Codes',
    'admins.banners': 'Banners',
    'admins.reports': 'Reports',
    'admins.notifications': 'Notifications',
    'admins.settings': 'Settings',
    'admins.usernameRequired': 'Username is required',
    'admins.usernameMinLength': 'Username must be at least 3 characters',
    'admins.emailRequired': 'Email is required',
    'admins.emailInvalid': 'Please enter a valid email address',
    'admins.permissionsRequired': 'At least one permission must be selected',
    'admins.usernameExists': 'Username already exists',
    'admins.emailExists': 'Email already exists',
    'admins.cancel': 'Cancel',
    'admins.emailStatus': 'Email Status',
    'admins.verified': 'Verified',
    'admins.pendingVerification': 'Pending Verification',
    'admins.sendEmail': 'Send Email',
    'admins.resetPassword.title': 'Send Password Reset Email',
    'admins.resetPassword.message': 'Are you sure you want to send a password reset email?',
    
    // Albums
    'albums.title': 'Album Management',
    'albums.subtitle': 'Manage your album collection',
    'albums.backToAlbums': 'Back to Albums',
    'cards.backToCards': 'Back to Cards',
    'albums.notFound': 'Album not found',
    'albums.errorLoadAlbumCards': 'Failed to load album and cards',
    'albums.search': 'Search albums...',
    'albums.filter': 'Filter',
    'albums.gridView': 'Grid View',
    'albums.tableView': 'Table View',
    'albums.loading': 'Fetching albums data...',
    'albums.errorLoading': 'Error loading albums',
    'albums.noResults': 'No albums found',
    'albums.name': 'Name',
    'albums.description': 'Description',
    'albums.category': 'Category',
    'albums.totalCards': 'Total Cards',
    'albums.createdDate': 'Created Date',
    'albums.status': 'Status',
    'albums.actions': 'Actions',
    'albums.header.image': 'Image',
    'albums.header.albumId': 'Album ID',
    'albums.header.name': 'Name',
    'albums.header.cardsCount': 'Cards Count',
    'albums.header.actions': 'Actions',
    'albums.edit': 'Edit',
    'albums.delete': 'Delete',
    'albums.view': 'View',
    'albums.confirmDelete': 'Are you sure you want to delete this album?',
    'albums.allCategories': 'All Categories',
    'albums.nature': 'Nature',
    'albums.sports': 'Sports',
    'albums.technology': 'Technology',
    'albums.art': 'Art',
    'albums.history': 'History',
    'albums.science': 'Science',
    'albums.allStatuses': 'All Statuses',
    'albums.active': 'Active',
    'albums.inactive': 'Inactive',
    'albums.draft': 'Draft',
    'albums.published': 'Published',
    'albums.previous': 'Previous',
    'albums.next': 'Next',
    'albums.showing': 'Showing',
    'albums.to': 'to',
    'albums.of': 'of',
    'albums.results': 'results',
    'albums.albumDetails': 'Album Details',
    'albums.albumInformation': 'Album Information',
    'albums.cardsList': 'Cards List',
    'albums.addNew': 'Add New Album',
    'albums.createAlbum': 'Create Album',
    'albums.editAlbum': 'Edit Album',
    'albums.imageUrl': 'Image URL',
    'albums.selectCategory': 'Select Category',
    'albums.selectStatus': 'Select Status',
    'albums.cardsInAlbum': 'Cards in Album',
    'albums.addCards': 'Add Cards',
    'albums.removeCard': 'Remove Card',
    'albums.cardCount': 'Card Count',
    'albums.completionRate': 'Completion Rate',
    'albums.popularityScore': 'Popularity Score',
    'albums.searchPlaceholder': 'Search albums...',
    'albums.filters': 'Filters',
    'albums.utilization': 'Utilization',
    'albums.capacity': 'Capacity',
    'albums.noCardsYet': 'No cards in this album yet',
    'albums.startAddingCards': 'Start by adding some cards to this album',
    'albums.allAlbums': 'All Albums',
    'albums.activeOnly': 'Active Only',
    'albums.inactiveOnly': 'Inactive Only',
    'albums.minCapacity': 'Min Capacity',
    'albums.maxCapacity': 'Max Capacity',
    'albums.minCapacityPlaceholder': 'Min capacity',
    'albums.maxCapacityPlaceholder': 'Max capacity',
    'albums.utilized': 'utilized',
    'albums.more': 'more',
    'albums.viewDetails': 'View Details',
    'albums.deleteAlbum': 'Delete Album',
    'albums.album': 'Album',
    'albums.tags': 'Tags',
    'albums.currentCount': 'Current Count',
    'albums.cards': 'cards',
    'albums.close': 'Close',
    'albums.enterAlbumName': 'Enter album name...',
    'albums.enterAlbumDescription': 'Enter album description...',
    'albums.enterMaxCapacity': 'Enter maximum capacity...',
    'albums.addTag': 'Add a tag...',
    'albums.add': 'Add',
    'albums.cancel': 'Cancel',
    'albums.updateAlbum': 'Update Album',

    // Store
    'store.title': 'Store Management',
    'store.subtitle': 'Manage your stock inventory and card packs',
    'store.addPack': 'Add New Pack',
    'store.createPack': 'Create Pack',
    'store.packId': 'Pack ID',
    'store.packIdRequired': 'Pack ID is required to create the document with that ID.',
    'store.packIdInvalidChars': 'Pack ID cannot contain /. Please use a valid identifier.',
    'store.failedCreatePack': 'Failed to create pack. Please try again.',
    'store.totalPacks': 'Total Packs',
    'store.totalPacksDesc': 'Card packs available',
    'store.totalValue': 'Total Value',
    'store.totalValueDesc': 'Combined pack value',
    'store.averagePrice': 'Average Price',
    'store.averagePriceDesc': 'Per pack',
    'store.searchPlaceholder': 'Search packs...',
    'store.confirmDelete': 'Delete this pack?',
    'store.deleteFailed': 'Failed to delete pack',
    'store.packDetails': 'Pack Details',
    'store.stockNumber': 'Stock Number',
    'store.price': 'Price',
    'store.linkedAlbum': 'Linked Album',
    'store.none': 'None',
    'store.noImage': 'No image',
    'store.editPack': 'Edit Pack',
    'store.noPacksFound': 'No packs found',
    'store.tryAdjustingSearch': 'Try adjusting your search',
    'store.getStartedAddPack': 'Get started by adding your first pack to the inventory.',
    
    // Cards
    'cards.title': 'Card Management',
    'cards.search': 'Search cards...',
    'cards.filter': 'Filter',
    'cards.gridView': 'Grid View',
    'cards.tableView': 'Table View',
    'cards.name': 'Name',
    'cards.description': 'Description',
    'cards.cardId': 'Card ID',
    'cards.points': 'Points',
    'cards.actions': 'Actions',
    'cards.edit': 'Edit',
    'cards.delete': 'Delete',
    'cards.collected': 'Collected',
    'cards.confirmDelete': 'Are you sure you want to delete this card?',
    'cards.allRarities': 'All Rarities',
    'cards.common': 'Common',
    'cards.uncommon': 'Uncommon',
    'cards.rare': 'Rare',
    'cards.legendary': 'Legendary',
    'cards.allTypes': 'All Types',
    'cards.creature': 'Creature',
    'cards.spell': 'Spell',
    'cards.item': 'Item',
    'cards.weapon': 'Weapon',
    'cards.previous': 'Previous',
    'cards.next': 'Next',
    'cards.showing': 'Showing',
    'cards.to': 'to',
    'cards.of': 'of',
    'cards.results': 'results',
    'cards.cardDetails': 'Card Details',
    'cards.cardEvolution': 'Card Evolution',
    'cards.evolutionPlaceholder': 'Card evolution information will be displayed here',
    'cards.albumPlacement': 'Album Placement',
    'cards.albumPlacementPlaceholder': 'Album placement information will be displayed here',
    'cards.addNew': 'Add New Card',
    'cards.addCard': 'Add Card',
    'cards.editCard': 'Edit Card',
    'cards.imageUrl': 'Image URL',
    'cards.album': 'Album',
    'cards.cardsTotal': 'cards total',
    'cards.inAlbum': 'in',
    'cards.albumCollection': 'Album Collection',
    'cards.allAlbums': 'All Albums',
    'cards.searchCards': 'Search Cards',
    'cards.searchPlaceholder': 'Search by name or description...',
    'cards.errorLoadCards': 'Failed to load cards',
    'cards.errorDeleteCard': 'Failed to delete card',
    'cards.errorSelectAlbum': 'Please select an album for the card',
    'cards.errorSaveCard': 'Failed to save card',
    'cards.fetchingCards': 'Fetching Cards data...',
    'cards.countLabel': 'cards',
    'cards.enterUniqueCardId': 'Enter unique card ID',
    'cards.requiredIdName': 'Card ID and name are required',
    'cards.createSuccess': 'Card created successfully!',
    'cards.errorCreateCard': 'Failed to create card',
    'cards.updateSuccess': 'Card updated successfully!',
    'cards.errorUpdateCard': 'Failed to update card',
    'cards.deleteSuccess': 'Card deleted successfully!',
    'cards.deleteConfirmExtended': 'Are you sure you want to delete this card? This action cannot be undone and the card will be removed from the album.',
    'cards.cardImage': 'Card Image',
    'cards.detailsTab': 'Card Details',
    'cards.detailsTabDescription': 'View and edit card information',
    'cards.information': 'Card Information',
    'cards.type': 'Type',
    'cards.card': 'Card',
    'cards.noCardsFound': 'No cards found',
    'cards.tryAdjustingSearch': 'Try adjusting your search terms',
    'cards.deleteCard': 'Delete Card',
    'cards.addNewCard': 'Add New Card',
    'cards.cardName': 'Card Name',
    'cards.autoGenerated': 'Auto-generated when card is created',
    'cards.enterCardName': 'Enter card name',
    'cards.cardImagesVariants': 'Card Images (5 variants)',
    'cards.uploadVariantsHelp': 'Upload bronze, silver, gold, titanium, and diamond images.',
    'cards.variant.bronze': 'Bronze',
    'cards.variant.silver': 'Silver',
    'cards.variant.gold': 'Gold',
    'cards.variant.titanium': 'Titanium',
    'cards.variant.diamond': 'Diamond',
    'cards.selectBronzeImage': 'Select Bronze image',
    'cards.selectSilverImage': 'Select Silver image',
    'cards.selectGoldImage': 'Select Gold image',
    'cards.selectTitaniumImage': 'Select Titanium image',
    'cards.selectDiamondImage': 'Select Diamond image',
    'cards.allowedTypesNote': 'Allowed types: JPG, PNG, WEBP. Max size: 5MB each.',
    'cards.error.invalidFileType': 'Invalid file type. Use JPG, PNG, or WEBP.',
    'cards.error.fileTooLarge': 'File too large. Max size is 5MB.',

    'cards.enterDescription': 'Enter card description',
    'cards.cardImages': 'Card Images',
    'card.enterDescription': 'Enter card description',



    'cards.typePlaceholder': 'e.g., Character, Spell, Item',
    'cards.epic': 'Epic',
    'cards.imageUrlPlaceholder': 'https://example.com/image.jpg',
    'cards.createCard': 'Add Card',
    
    // Codes
    'codes.title': 'Code Management',
    'codes.add': 'Add Code',
    'codes.bulkUpload': 'Bulk Upload',
    'codes.generate': 'Generate Codes',
    'codes.generateCodes': 'Generate New Codes',
    'codes.import': 'Import',
    'codes.export': 'Export',
    'codes.exportConfirmation': 'Codes will be exported to CSV format',
    'codes.fileUploaded': 'File {filename} uploaded successfully',
    'codes.search': 'Search codes...',
    'codes.filter': 'Filter',
    'codes.code': 'Code',
    'codes.type': 'Type',
    'codes.status': 'Status',
    'codes.createdAt': 'Created At',
    'codes.usedAt': 'Used At',
    'codes.usedBy': 'Used By',
    'codes.actions': 'Actions',
    'codes.confirmDelete': 'Are you sure you want to delete this code?',
    'codes.allTypes': 'All Types',
    'codes.alphanumeric': 'Alphanumeric',
    'codes.qr': 'QR Code',
    'codes.allStatuses': 'All Statuses',
    'codes.active': 'Active',
    'codes.used': 'Used',
    'codes.expired': 'Expired',
    'codes.previous': 'Previous',
    'codes.next': 'Next',
    'codes.showing': 'Showing',
    'codes.to': 'to',
    'codes.of': 'of',
    'codes.results': 'results',
    'codes.quantity': 'Quantity',
    'codes.prefix': 'Prefix',
    'codes.length': 'Length',
    'codes.lengthNote': 'Total length including prefix',
    'codes.redeemCodesTitle': 'Redeem Codes',
    'codes.redeemCodesTab': 'Redeem Codes',
    'codes.redeemCodesTabDescription': 'Manage redeem codes for this card',
    'codes.qrCodesTab': 'QR Codes',
    'codes.qrCodesTabDescription': 'Generate and download QR codes',
    'codes.totalCodes': 'Total Codes',
    'codes.total': 'Total',
    'codes.importCsvExcel': 'Import CSV/Excel',
    'codes.codesSelectedLabel': 'codes selected',
    'codes.qrCodesSelectedSuffix': 'QR codes selected',
    'codes.available': 'Available',
    'codes.qrManagementTitle': 'QR Code Management',
    'codes.qrCodes': 'QR Codes',
    'codes.downloadSelected': 'Download Selected',
    'codes.exportSelected': 'Export Selected',
    'codes.downloadAllQRCodes': 'Download All QR Codes',
    'codes.noQrCodesYet': 'No QR Codes Yet',
    'codes.noQrCodesDescription': 'Add some redeem codes first to generate QR codes automatically.',
    'codes.noCodesYet': 'No codes yet',
    'codes.noCodesYetDescription': 'Start by adding some redeem codes to this card. You can add them individually or import from a CSV/Excel file.',
    'codes.addCodes': 'Add Codes',
    'codes.importCodes': 'Import Codes',
    'codes.exportCodes': 'Export Codes',
    'codes.addPromoCode': 'Add Promo Code',
    'codes.addRedeemCode': 'Add Redeem Code',
    'codes.codeLabel': 'Code',
    'codes.enterCodePlaceholder': 'Enter redeem code...',
    'codes.importTitle': 'Import Redeem Codes',
    'codes.importHelpText': 'Upload an Excel or CSV file with redeem codes. The first column should contain the alphanumeric codes.',
    'codes.exportTitle': 'Export Redeem Codes',
    'codes.exportSelectedCodes': 'Export selected codes',
    'codes.exportAllCodesFor': 'Export all codes for',
    'codes.withQrCodes': 'with their QR codes.',
    'codes.downloadQRCode': 'Download QR Code',
    'codes.deleteCode': 'Delete Code',
    'codes.errorImportFile': 'Error importing file. Please check the format.',
    'codes.errorDeleteCode': 'Failed to delete code',
    'codes.fetchingRedeemCodes': 'Fetching Redeem Codes data...',
    'codes.redeemCodesPageSubtitle': 'Manage redeem codes and QR codes',
    
    // Banners
    'banners.title': 'Banner Management',
    'banners.add': 'Add Banner',
    'banners.edit': 'Edit Banner',
    'banners.delete': 'Delete Banner',
    'banners.confirmDelete': 'Are you sure you want to delete this banner?',
    'banners.name': 'Name',
    'banners.image': 'Image',
    'banners.url': 'URL',
    'banners.startDate': 'Start Date',
    'banners.endDate': 'End Date',
    'banners.active': 'Active',
    'banners.inactive': 'Inactive',
    'banners.preview': 'Preview',
    'banners.search': 'Search banners...',
    'banners.filter': 'Filter',
    'banners.status': 'Status',
    'banners.allStatuses': 'All Statuses',
    'banners.previous': 'Previous',
    'banners.next': 'Next',
    'app.close': 'Close',
    
    // Reports
    'reports.title': 'Reports & Statistics',
    'reports.newUsers': 'New Users',
    'reports.sales': 'Sales',
    'reports.userActivity': 'User Activity',
    'reports.export': 'Export',
    'reports.exportConfirmation': 'Reports will be exported to CSV format',
    'reports.period': 'Period',
    'reports.daily': 'Daily',
    'reports.weekly': 'Weekly',
    'reports.monthly': 'Monthly',
    'reports.yearly': 'Yearly',
    'reports.fromLastMonth': 'from last month',
    'reports.recentActivity': 'Recent Activity',
    'app.action': 'Action',
    'app.details': 'Details',
    
    // Notifications
    'notifications.title': 'Push Notifications',
    'notifications.compose': 'Compose',
    'notifications.target': 'Target',
    'notifications.global': 'Global',
    'notifications.specific': 'Specific Users',
    'notifications.preview': 'Preview',
    'notifications.send': 'Send',
    'notifications.history': 'History',
    'notifications.message': 'Message',
    'notifications.title_field': 'Title',
    'notifications.body': 'Body',
    'notifications.status': 'Status',
    'notifications.sent': 'Sent',
    'notifications.scheduled': 'Scheduled',
    'notifications.confirmSend': 'Are you sure you want to send this notification?',
    'notifications.success': 'Notification sent successfully',
    'notifications.selectUsers': 'Select Users',
    'notifications.searchUsers': 'Search users',
    'notifications.selectedUsers': 'Selected Users',
    'notifications.date': 'Date',
    'notifications.time': 'Time',
    'notifications.scheduleFor': 'Schedule for',
    'notifications.country': 'Country',
    'notifications.state': 'State',
    'notifications.city': 'City',
    'notifications.loadingUsers': 'Loading users...',
    'notifications.noUsersFound': 'No users found',
    
    // Settings
    'settings.title': 'Settings',
    'settings.general': 'General',
    'settings.profile': 'Profile',
    'settings.security': 'Security',
    'settings.generalSettings': 'General Settings',
    'settings.profileSettings': 'Profile Settings',
    'settings.securitySettings': 'Security Settings',
    'settings.language': 'Language',
    'settings.languageDescription': 'Choose your preferred language for the interface',
    'settings.theme': 'Theme',
    'settings.themeDescription': 'Choose between light and dark theme',
    'settings.lightTheme': 'Light',
    'settings.darkTheme': 'Dark',
    'settings.savePreferences': 'Save Preferences',
    'settings.saveSuccess': 'Settings saved successfully',
    'settings.changesDetected': 'Changes detected - settings will be applied immediately',
    'settings.name': 'Name',
    'settings.email': 'Email',
    'settings.phone': 'Phone',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm Password',
    'settings.updatePassword': 'Update Password',
    'settings.saveProfile': 'Save Profile',
    'settings.defaultName': 'Admin User',
    'settings.defaultEmail': 'admin@example.com',
    'settings.defaultPhone': '+1 (555) 123-4567',
    'settings.currentPasswordRequired': 'Current password is required',
    'settings.newPasswordRequired': 'New password is required',
    'settings.passwordMinLength': 'Password must be at least 8 characters',
    'settings.confirmPasswordRequired': 'Please confirm your password',
    'settings.passwordsDoNotMatch': 'Passwords do not match',
    'settings.passwordUpdateSuccess': 'Password updated successfully',
    'settings.profileUpdateSuccess': 'Profile updated successfully',
    
    // Additional
    'app.date': 'Date',
    'users.loggedIn': 'Logged in',
  },
  es: {
    // Common
    'app.title': 'sglapp',
    'app.loading': 'Cargando...',
    'app.retry': 'Reintentar',
    'app.error': 'Ocurrió un error',
    'app.save': 'Guardar',
    'app.cancel': 'Cancelar',
    'app.delete': 'Eliminar',
    'app.edit': 'Editar',
    'app.view': 'Ver',
    'app.search': 'Buscar',
    'app.filter': 'Filtrar',
    'app.filters': 'Filtros',
    'app.sort': 'Ordenar',
    'app.actions': 'Acciones',
    'app.confirm': 'Confirmar',
    'app.back': 'Atrás',
    'app.next': 'Siguiente',
    'app.previous': 'Anterior',
    'app.refresh': 'Actualizar',
    'app.showing': 'Mostrando',
    'app.to': 'a',
    'app.of': 'de',
    'app.results': 'resultados',
    'app.page': 'Página',
    'app.yes': 'Sí',
    'app.no': 'No',
    'app.rights': 'Todos los Derechos Reservados',
    'app.create': 'Crear',
    'app.update': 'Actualizar',
    'app.export': 'Exportar',
    'app.import': 'Importar',
    'app.download': 'Descargar',
    'app.upload': 'Subir',
    'app.remove': 'Eliminar',
    'app.selectAll': 'Seleccionar todo',
    'app.clearSelection': 'Limpiar selección',
    'app.filterOptions': 'Opciones de filtro',
    'app.fromDate': 'Desde fecha',
    'app.toDate': 'Hasta fecha',
    
    // Navigation
    'nav.dashboard': 'Tablero',
    'nav.users': 'Usuarios',
    'nav.cards': 'Tarjetas y Álbumes',
    'nav.admins': 'Gestión de Administradores',
    'nav.albums': 'Álbumes',
    'nav.codes': 'QR y Códigos',
    'nav.banners': 'Banners',
    'nav.store': 'Tienda',
    'nav.sales': 'Ventas',
    'nav.reports': 'Informes',
    'nav.notifications': 'Notificaciones',
    'nav.settings': 'Configuración',
    'nav.logout': 'Cerrar Sesión',

    // Dashboard
    'dashboard.overview': 'Resumen del Panel',
    'dashboard.subtitle': 'Monitorea el rendimiento de tu panel de administración y estadísticas de usuarios',
    'dashboard.totalUsers': 'Total de Usuarios',
    'dashboard.totalUsersDesc': 'Usuarios registrados',
    'dashboard.totalCards': 'Total de Cartas',
    'dashboard.totalCardsDesc': 'Cartas en el sistema',
    'dashboard.totalAlbums': 'Total de Álbumes',
    'dashboard.totalAlbumsDesc': 'Álbumes en el sistema',
    'dashboard.totalQrCodes': 'Total de Códigos QR',
    'dashboard.totalQrCodesDesc': 'Documentos de códigos canjeables',
    'dashboard.totalPacks': 'Total de Paquetes',
    'dashboard.totalPacksDesc': 'Paquetes en la tienda',
    'dashboard.totalBanners': 'Total de Banners',
    'dashboard.totalBannersDesc': 'Banners en el sistema',
    'dashboard.totalSales': 'Ventas Totales',
    'dashboard.totalSalesDesc': 'Suma de precios de ventas',
    'dashboard.last7Days': 'Últimos 7 días',
    'dashboard.last30Days': 'Últimos 30 días',
    'dashboard.last90Days': 'Últimos 90 días',
    'dashboard.lastYear': 'Último año',
    
    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.forgotPassword': 'Olvidó su Contraseña?',
    'auth.invalidCredentials': 'Correo o contraseña inválidos',
    'auth.emailRequired': 'El correo electrónico es requerido',
    'auth.emailInvalid': 'Por favor ingrese un correo válido',
    'auth.passwordRequired': 'La contraseña es requerida',
    'auth.passwordTooShort': 'La contraseña debe tener al menos 6 caracteres',
    'auth.rememberMe': 'Recordarme',
    'auth.demoCredentials': 'Credenciales de demostración',
    
    // Users
    'users.title': 'Gestión de Usuarios',
    'users.description': 'Gestiona usuarios y sus detalles',
    'users.search': 'Buscar usuarios...',
    'users.searchPlaceholder': 'Buscar usuarios...',
    'users.filter': 'Filtrar',
    'users.username': 'Nombre de Usuario',
    'users.email': 'Correo Electrónico',
    'users.points': 'Puntos',
    'users.status': 'Estado',
    'users.registrationDate': 'Fecha de Registro',
    'users.actions': 'Acciones',
    'users.edit': 'Editar',
    'users.delete': 'Eliminar',
    'users.activate': 'Activar',
    'users.deactivate': 'Desactivar',
    'users.suspend': 'Suspender',
    'users.unsuspend': 'Reactivar',
    'users.confirmDelete': 'Está seguro de que desea eliminar este usuario?',
    'users.allStatuses': 'Todos los Estados',
    'users.active': 'Activo',
    'users.inactive': 'Inactivo',
    'users.suspended': 'Suspendido',
    'users.allPoints': 'Todos los Puntos',
    'users.lowPoints': 'Puntos Bajos',
    'users.mediumPoints': 'Puntos Medios',
    'users.highPoints': 'Puntos Altos',
    'users.previous': 'Anterior',
    'users.next': 'Siguiente',
    'users.showing': 'Mostrando',
    'users.to': 'a',
    'users.of': 'de',
    'users.results': 'resultados',
    'users.userDetails': 'Detalles del Usuario',
    'users.profileInformation': 'Información del Perfil',
    'users.activity': 'Actividad del Usuario',
    'users.activityPlaceholder': 'Los datos de actividad del usuario se mostrarán aquí',
    'users.collectedCards': 'Tarjetas Coleccionadas',
    'users.collectedCardsPlaceholder': 'Las tarjetas coleccionadas por el usuario se mostrarán aquí',
    'users.add': 'Agregar Usuario',
    'users.addInfluencer': 'Agregar Influencer',
    'users.cardsOwned': 'Cartas Poseídas',
    'users.cardTypesAndCounts': 'Tipos de Cartas y Cantidades',
    'users.addNewUser': 'Agregar Nuevo Usuario',
    'users.addNewInfluencer': 'Agregar Nuevo Influencer',
    'users.isInfluencer': 'Es Influencer',
    'users.firstName': 'Nombre',
    'users.lastName': 'Apellido',
    'users.enterFirstName': 'Ingrese nombre',
    'users.enterLastName': 'Ingrese apellido',
    'users.enterEmail': 'Ingrese dirección de correo',
    'users.enterPassword': 'Ingrese contraseña',
    'users.dateOfBirth': 'Fecha de Nacimiento',
    'users.country': 'País',
    'users.state': 'Estado',
    'users.city': 'Ciudad',
    'users.gender': 'Género',
    'users.language': 'Idioma',
    'users.selectCountry': 'Seleccionar País',
    'users.selectGender': 'Seleccionar Género',
    'users.selectLanguage': 'Seleccionar Idioma',
    'users.male': 'Masculino',
    'users.female': 'Femenino',
    'users.other': 'Otro',
    'users.english': 'Inglés',
    'users.spanish': 'Español',
    'users.passwordMinLength': 'La contraseña debe tener al menos 8 caracteres',
    'users.addUser': 'Agregar Usuario',

    // Sales
    'sales.title': 'Informe de Ventas',
    'sales.subtitle': 'Gestiona y visualiza todas las transacciones de ventas',
    'sales.exportExcel': 'Exportar Excel',
    'sales.exportCSV': 'Exportar CSV',
    'sales.deleteSelected': 'Eliminar Seleccionados',
    'sales.pinUnpin': 'Fijar/Desfijar',
    'sales.ariaDeleteSelected': 'Eliminar seleccionados',
    'sales.ariaPinUnpinSelected': 'Fijar o desfijar seleccionados',
    'sales.searchPlaceholder': 'Buscar por ID de venta o usuario...',
    'sales.filters': 'Filtros',
    'sales.referrerName': 'Nombre del Referente',
    'sales.fromDate': 'Fecha Desde',
    'sales.toDate': 'Fecha Hasta',
    'sales.minAmount': 'Monto Mínimo',
    'sales.maxAmount': 'Monto Máximo',
    'sales.minAmountPlaceholder': '0.00',
    'sales.maxAmountPlaceholder': '999.99',
    'sales.resetFilters': 'Restablecer Filtros',
    'sales.filterSummary.referrer': 'Referente:',
    'sales.filterSummary.from': 'Desde:',
    'sales.filterSummary.to': 'Hasta:',
    'sales.filtering': 'Filtrando...',
    'sales.loading': 'Cargando ventas...',
    'sales.noResults': 'No se encontraron ventas para los filtros actuales.',
    'sales.resolving': 'Resolviendo…',
    'sales.allReferrers': 'Todos los Referentes',
    'sales.selectAllOnPage': 'Seleccionar todo en la página',
    'sales.selectSale': 'Seleccionar venta {id}',
    'sales.pinned': 'Fijado',
    'sales.noReferrer': 'Sin Referente',
    'sales.unknownUser': 'Usuario desconocido',
    'sales.header.sr': 'Nº',
    'sales.header.saleId': 'ID de Venta',
    'sales.header.username': 'Usuario',
    'sales.header.refererName': 'Nombre del Referente',
    'sales.header.createdAt': 'Fecha de Creación',
    'sales.header.price': 'Precio',
    'sales.realtimeUnavailable': 'Actualización en tiempo real no disponible. Mostrando el último snapshot.',
    'sales.unableToLoad': 'No se pueden cargar las ventas. Verifique su red o autenticación.',
    'sales.initRealtimeFailed': 'Error al inicializar el feed de ventas en tiempo real.',
    'sales.refreshFailed': 'Actualización fallida. Por favor verifica tu conexión.',
    'sales.confirmDeleteSelected': 'Eliminar {count} venta(s) seleccionadas? Esta acción no se puede deshacer.',
    'sales.deleteResultMixed': 'Eliminadas {success} venta(s), {failed} fallidas.',
    'sales.deleteResult': 'Eliminadas {success} venta(s).',
    'sales.pinToggleResult': 'Fijadas {pinned}, desfijadas {unpinned}.',
    'sales.sheetName': 'Informe de Ventas',
    'auth.signInRequired': 'Es posible que se requiera iniciar sesión.',
    
    // Admins
    'admins.title': 'Gestión de Administradores',
    'admins.search': 'Buscar administradores...',
    'admins.filter': 'Filtrar',
    'admins.username': 'Nombre de Usuario',
    'admins.email': 'Correo Electrónico',
    'admins.lastLogin': 'Último Acceso',
    'admins.createdDate': 'Fecha de Creación',
    'admins.permissions': 'Permisos',
    'admins.actions': 'Acciones',
    'admins.edit': 'Editar',
    'admins.delete': 'Eliminar',
    'admins.view': 'Ver',
    'admins.confirmDelete': 'Está seguro de que desea eliminar este administrador?',
    'admins.previous': 'Anterior',
    'admins.next': 'Siguiente',
    'admins.showing': 'Mostrando',
    'admins.to': 'a',
    'admins.of': 'de',
    'admins.results': 'resultados',
    'admins.loading': 'Cargando administradores...',
    'admins.loadingFor': 'Cargando administradores para',
    'admins.adminDetails': 'Detalles del Administrador',
    'admins.profileInformation': 'Información del Perfil',
    'admins.permissionsList': 'Lista de Permisos',
    'admins.addNew': 'Agregar Nuevo Administrador',
    'admins.editAdmin': 'Editar Administrador',
    'admins.password': 'Contraseña',
    'admins.confirmPassword': 'Confirmar Contraseña',
    'admins.selectPermissions': 'Seleccionar Permisos',
    'admins.allPermissions': 'Todos los Permisos',
    'admins.enterUsername': 'Ingrese nombre de usuario',
    'admins.enterEmail': 'Ingrese dirección de correo electrónico',
    'admins.users': 'Usuarios',
    'admins.cards': 'Tarjetas',
    'admins.albums': 'Álbumes',
    'admins.codes': 'Códigos',
    'admins.banners': 'Banners',
    'admins.reports': 'Informes',
    'admins.notifications': 'Notificaciones',
    'admins.settings': 'Configuración',
    'admins.usernameRequired': 'El nombre de usuario es requerido',
    'admins.usernameMinLength': 'El nombre de usuario debe tener al menos 3 caracteres',
    'admins.emailRequired': 'El correo electrónico es requerido',
    'admins.emailInvalid': 'Por favor ingrese una dirección de correo válida',
    'admins.permissionsRequired': 'Al menos un permiso debe ser seleccionado',
    'admins.usernameExists': 'El nombre de usuario ya existe',
    'admins.emailExists': 'El correo electrónico ya existe',
    
    // Albums
    'albums.title': 'Gestión de Álbumes',
    'albums.subtitle': 'Gestiona tu colección de álbumes',
    'albums.backToAlbums': 'Volver a Álbumes',
    'cards.backToCards': 'Volver a Tarjetas',
    'albums.notFound': 'Álbum no encontrado',
    'albums.errorLoadAlbumCards': 'Error al cargar el álbum y las tarjetas',
    'albums.search': 'Buscar álbumes...',
    'albums.filter': 'Filtrar',
    'albums.gridView': 'Vista de Cuadrícula',
    'albums.tableView': 'Vista de Tabla',
    'albums.loading': 'Obteniendo datos de álbumes...',
    'albums.errorLoading': 'Error al cargar los álbumes',
    'albums.noResults': 'No se encontraron álbumes',
    'albums.name': 'Nombre',
    'albums.description': 'Descripción',
    'albums.category': 'Categoría',
    'albums.totalCards': 'Total de Tarjetas',
    'albums.createdDate': 'Fecha de Creación',
    'albums.status': 'Estado',
    'albums.actions': 'Acciones',
    'albums.header.image': 'Imagen',
    'albums.header.albumId': 'ID del Álbum',
    'albums.header.name': 'Nombre',
    'albums.header.cardsCount': 'Cantidad de Tarjetas',
    'albums.header.actions': 'Acciones',
    'albums.edit': 'Editar',
    'albums.delete': 'Eliminar',
    'albums.view': 'Ver',
    'albums.confirmDelete': 'Está seguro de que desea eliminar este álbum?',
    'albums.allCategories': 'Todas las Categorías',
    'albums.nature': 'Naturaleza',
    'albums.sports': 'Deportes',
    'albums.technology': 'Tecnología',
    'albums.art': 'Arte',
    'albums.history': 'Historia',
    'albums.science': 'Ciencia',
    'albums.allStatuses': 'Todos los Estados',
    'albums.active': 'Activo',
    'albums.inactive': 'Inactivo',
    'albums.draft': 'Borrador',
    'albums.published': 'Publicado',
    'albums.previous': 'Anterior',
    'albums.next': 'Siguiente',
    'albums.showing': 'Mostrando',
    'albums.to': 'a',
    'albums.of': 'de',
    'albums.results': 'resultados',
    'albums.albumDetails': 'Detalles del Álbum',
    'albums.albumInformation': 'Información del Álbum',
    'albums.cardsList': 'Lista de Tarjetas',
    'albums.addNew': 'Agregar Nuevo Álbum',
    'albums.createAlbum': 'Crear Álbum',
    'albums.editAlbum': 'Editar Álbum',
    'albums.imageUrl': 'URL de Imagen',
    'albums.selectCategory': 'Seleccionar Categoría',
    'albums.selectStatus': 'Seleccionar Estado',
    'albums.cardsInAlbum': 'Tarjetas en el Álbum',
    'albums.addCards': 'Agregar Tarjetas',
    'albums.removeCard': 'Eliminar Tarjeta',
    'albums.cardCount': 'Cantidad de Tarjetas',
    'albums.completionRate': 'Tasa de Finalización',
    'albums.popularityScore': 'Puntuación de Popularidad',
    'albums.searchPlaceholder': 'Buscar álbumes...',
    'albums.filters': 'Filtros',
    'albums.utilization': 'Utilización',
    'albums.capacity': 'Capacidad',
    'albums.noCardsYet': 'Aún no hay tarjetas en este álbum',
    'albums.startAddingCards': 'Comienza agregando algunas tarjetas a este álbum',
    'albums.allAlbums': 'Todos los Álbumes',
    'albums.activeOnly': 'Solo Activos',
    'albums.inactiveOnly': 'Solo Inactivos',
    'albums.minCapacity': 'Capacidad Mínima',
    'albums.maxCapacity': 'Capacidad Máxima',
    'albums.minCapacityPlaceholder': 'Capacidad mínima',
    'albums.maxCapacityPlaceholder': 'Capacidad máxima',
    'albums.utilized': 'utilizado',
    'albums.more': 'más',
    'albums.viewDetails': 'Ver Detalles',
    'albums.deleteAlbum': 'Eliminar Álbum',
    'albums.album': 'Álbum',
    'albums.tags': 'Etiquetas',
    'albums.currentCount': 'Cantidad Actual',
    'albums.cards': 'tarjetas',
    'albums.close': 'Cerrar',
    'albums.enterAlbumName': 'Ingrese el nombre del álbum...',
    'albums.enterAlbumDescription': 'Ingrese la descripción del álbum...',
    'albums.enterMaxCapacity': 'Ingrese la capacidad máxima...',
    'albums.addTag': 'Agregar una etiqueta...',
    'albums.add': 'Agregar',
    'albums.cancel': 'Cancelar',
    'albums.updateAlbum': 'Actualizar Álbum',

    // Store
    'store.title': 'Gestión de Tienda',
    'store.subtitle': 'Administra tu inventario y paquetes de cartas',
    'store.addPack': 'Agregar Nuevo Paquete',
    'store.totalPacks': 'Total de Paquetes',
    'store.totalPacksDesc': 'Paquetes de cartas disponibles',
    'store.totalValue': 'Valor Total',
    'store.totalValueDesc': 'Valor combinado de los paquetes',
    'store.averagePrice': 'Precio Promedio',
    'store.averagePriceDesc': 'Por paquete',
    'store.searchPlaceholder': 'Buscar paquetes...',
    'store.confirmDelete': '¿Eliminar este paquete?',
    'store.deleteFailed': 'No se pudo eliminar el paquete',
    'store.packDetails': 'Detalles del Paquete',
    'store.createPack': 'Crear Paquete',
    'store.packId': 'ID del Paquete',
    'store.packIdRequired': 'El ID del paquete es obligatorio para crear el documento con ese ID.',
    'store.packIdInvalidChars': 'El ID del paquete no puede contener /. Usa un identificador válido.',
    'store.failedCreatePack': 'Error al crear el paquete. Inténtalo de nuevo.',
    'store.stockNumber': 'Número de Stock',
    'store.price': 'Precio',
    'store.linkedAlbum': 'Álbum Vinculado',
    'store.none': 'Ninguno',
    'store.noImage': 'Sin imagen',
    'store.editPack': 'Editar Paquete',
    'store.noPacksFound': 'No se encontraron paquetes',
    'store.tryAdjustingSearch': 'Intenta ajustar tu búsqueda',
    'store.getStartedAddPack': 'Comienza agregando tu primer paquete al inventario.',
    
    // Cards
    'cards.title': 'Gestión de Tarjetas',
    'cards.search': 'Buscar tarjetas...',
    'cards.filter': 'Filtrar',
    'cards.gridView': 'Vista de Cuadrícula',
    'cards.tableView': 'Vista de Tabla',
    'cards.name': 'Nombre',
    'cards.description': 'Descripción',
    'cards.cardId': 'ID de Tarjeta',
    'cards.points': 'Puntos',
    'cards.actions': 'Acciones',
    'cards.edit': 'Editar',
    'cards.delete': 'Eliminar',
    'cards.collected': 'Recolectada',
    'cards.confirmDelete': 'Está seguro de que desea eliminar esta tarjeta?',
    'cards.allRarities': 'Todas las Rarezas',
    'cards.common': 'Común',
    'cards.uncommon': 'Poco Común',
    'cards.rare': 'Rara',
    'cards.legendary': 'Legendaria',
    'cards.allTypes': 'Todos los Tipos',
    'cards.creature': 'Criatura',
    'cards.spell': 'Hechizo',
    'cards.item': 'Objeto',
    'cards.weapon': 'Arma',
    'cards.previous': 'Anterior',
    'cards.next': 'Siguiente',
    'cards.showing': 'Mostrando',
    'cards.to': 'a',
    'cards.of': 'de',
    'cards.results': 'resultados',
    'cards.cardDetails': 'Detalles de la Tarjeta',
    'cards.cardEvolution': 'Evolución de la Tarjeta',
    'cards.evolutionPlaceholder': 'La información de evolución de la tarjeta se mostrará aquí',
    'cards.albumPlacement': 'Ubicación en el Álbum',
    'cards.albumPlacementPlaceholder': 'La información de ubicación en el álbum se mostrará aquí',
    'cards.addNew': 'Añadir Nueva Tarjeta',
    'cards.addCard': 'Añadir Tarjeta',
    'cards.editCard': 'Editar Tarjeta',
    'cards.imageUrl': 'URL de la Imagen',
    'cards.album': 'Álbum',
    'cards.cardsTotal': 'tarjetas en total',
    'cards.inAlbum': 'en',
    'cards.albumCollection': 'Colección de Álbumes',
    'cards.allAlbums': 'Todos los Álbumes',
    'cards.searchCards': 'Buscar Tarjetas',
    'cards.searchPlaceholder': 'Buscar por nombre o descripción...',
    'cards.errorLoadCards': 'Error al cargar las tarjetas',
    'cards.errorDeleteCard': 'Error al eliminar la tarjeta',
    'cards.errorSelectAlbum': 'Por favor seleccione un álbum para la tarjeta',
    'cards.errorSaveCard': 'Error al guardar la tarjeta',
    'cards.fetchingCards': 'Obteniendo datos de tarjetas...',
    'cards.countLabel': 'tarjetas',
    'cards.enterUniqueCardId': 'Ingrese ID único de la tarjeta',
    'cards.enterCardName': 'Ingrese nombre de la tarjeta',
    'cards.enterDescription': 'Ingrese descripción de la tarjeta',
    'cards.cardImages': 'Imágenes de la tarjeta',
    'card.enterDescription': 'Ingrese descripción de la tarjeta',
    'cards.cardImagesVariants': 'Imágenes de la tarjeta (5 variantes)',
    'cards.uploadVariantsHelp': 'Sube imágenes de bronce, plata, oro, titanio y diamante.',
    'cards.variant.bronze': 'Bronce',
    'cards.variant.silver': 'Plata',
    'cards.variant.gold': 'Oro',
    'cards.variant.titanium': 'Titanio',
    'cards.variant.diamond': 'Diamante',
    'cards.selectBronzeImage': 'Seleccionar imagen de Bronce',
    'cards.selectSilverImage': 'Seleccionar imagen de Plata',
    'cards.selectGoldImage': 'Seleccionar imagen de Oro',
    'cards.selectTitaniumImage': 'Seleccionar imagen de Titanio',
    'cards.selectDiamondImage': 'Seleccionar imagen de Diamante',
    'cards.allowedTypesNote': 'Tipos permitidos: JPG, PNG, WEBP. Tamaño máximo: 5MB cada uno.',
    'cards.error.invalidFileType': 'Tipo de archivo inválido. Usa JPG, PNG o WEBP.',
    'cards.error.fileTooLarge': 'Archivo demasiado grande. Tamaño máximo 5MB.',
    'cards.requiredIdName': 'El ID de la tarjeta y el nombre son obligatorios',
    'cards.createSuccess': '¡Tarjeta creada con éxito!',
    'cards.errorCreateCard': 'Error al crear la tarjeta',
    'cards.updateSuccess': '¡Tarjeta actualizada con éxito!',
    'cards.errorUpdateCard': 'Error al actualizar la tarjeta',
    'cards.deleteSuccess': '¡Tarjeta eliminada con éxito!',
    'cards.deleteConfirmExtended': '¿Está seguro de que desea eliminar esta tarjeta? Esta acción no se puede deshacer y la tarjeta se eliminará del álbum.',
    'cards.cardImage': 'Imagen de la tarjeta',
    'cards.detailsTab': 'Detalles de la Tarjeta',
    'cards.detailsTabDescription': 'Ver y editar información de la tarjeta',
    'cards.information': 'Información de la Tarjeta',
    'cards.type': 'Tipo',
    'cards.card': 'Tarjeta',
    'cards.noCardsFound': 'No se encontraron tarjetas',
    'cards.tryAdjustingSearch': 'Intenta ajustar tus términos de búsqueda',
    'cards.deleteCard': 'Eliminar Tarjeta',
    'cards.addFirstCard': 'Agregar Primera Carta',
    'cards.addNewCard': 'Agregar Nueva Carta',
    'cards.cardName': 'Nombre de la Carta',
    'cards.autoGenerated': 'Generado automáticamente cuando se crea la carta',
    'cards.typePlaceholder': 'ej., Personaje, Hechizo, Objeto',
    'cards.epic': 'Épico',
    'cards.imageUrlPlaceholder': 'https://ejemplo.com/imagen.jpg',
    'cards.rarity': 'Rareza',
    'cards.selectRarity': 'Seleccionar Rareza',
    'cards.selectType': 'Seleccionar Tipo',
    'cards.selectAlbum': 'Seleccionar Álbum',
    'cards.enterCardDescription': 'Ingrese la descripción de la tarjeta...',
    'cards.enterImageUrl': 'Ingrese la URL de la imagen...',
    'cards.enterPoints': 'Ingrese los puntos...',
    'cards.createCard': 'Crear Tarjeta',
    'cards.updateCard': 'Actualizar Tarjeta',
    'cards.close': 'Cerrar',
    'cards.cancel': 'Cancelar',
    'cards.add': 'Agregar',
    
    // Codes
    'codes.title': 'Gestión de Códigos',
    'codes.add': 'Añadir Código',
    'codes.bulkUpload': 'Carga Masiva',
    'codes.generate': 'Generar Códigos',
    'codes.generateCodes': 'Generar Nuevos Códigos',
    'codes.import': 'Importar',
    'codes.export': 'Exportar',
    'codes.exportConfirmation': 'Los códigos se exportarán en formato CSV',
    'codes.fileUploaded': 'Archivo {filename} cargado con éxito',
    'codes.search': 'Buscar códigos...',
    'codes.filter': 'Filtrar',
    'codes.code': 'Código',
    'codes.type': 'Tipo',
    'codes.status': 'Estado',
    'codes.createdAt': 'Fecha de Creación',
    'codes.usedAt': 'Fecha de Uso',
    'codes.usedBy': 'Usado Por',
    'codes.actions': 'Acciones',
    'codes.confirmDelete': 'Está seguro de que desea eliminar este código?',
    'codes.allTypes': 'Todos los Tipos',
    'codes.alphanumeric': 'Alfanumérico',
    'codes.qr': 'Código QR',
    'codes.allStatuses': 'Todos los Estados',
    'codes.active': 'Activo',
    'codes.used': 'Usado',
    'codes.expired': 'Expirado',
    'codes.previous': 'Anterior',
    'codes.next': 'Siguiente',
    'codes.showing': 'Mostrando',
    'codes.to': 'a',
    'codes.of': 'de',
    'codes.results': 'resultados',
    'codes.quantity': 'Cantidad',
    'codes.prefix': 'Prefijo',
    'codes.length': 'Longitud',
    'codes.lengthNote': 'Longitud total incluyendo prefijo',
    'codes.redeemCodesTitle': 'Códigos de Canje',
    'codes.redeemCodesTab': 'Códigos de Canje',
    'codes.redeemCodesTabDescription': 'Gestionar códigos de canje para esta tarjeta',
    'codes.qrCodesTab': 'Códigos QR',
    'codes.qrCodesTabDescription': 'Generar y descargar códigos QR',
    'codes.totalCodes': 'Códigos Totales',
    'codes.total': 'Total',
    'codes.importCsvExcel': 'Importar CSV/Excel',
    'codes.codesSelectedLabel': 'códigos seleccionados',
    'codes.qrCodesSelectedSuffix': 'códigos QR seleccionados',
    'codes.available': 'Disponible',
    'codes.qrManagementTitle': 'Gestión de Códigos QR',
    'codes.qrCodes': 'Códigos QR',
    'codes.downloadSelected': 'Descargar Seleccionados',
    'codes.exportSelected': 'Exportar Seleccionados',
    'codes.downloadAllQRCodes': 'Descargar todos los códigos QR',
    'codes.noQrCodesYet': 'Aún no hay códigos QR',
    'codes.noQrCodesDescription': 'Primero agrega algunos códigos de canje para generar códigos QR automáticamente.',
    'codes.noCodesYet': 'Aún no hay códigos',
    'codes.noCodesYetDescription': 'Comienza agregando algunos códigos de canje a esta tarjeta. Puedes agregarlos individualmente o importar desde un archivo CSV/Excel.',
    'codes.addCodes': 'Añadir Códigos',
    'codes.importCodes': 'Importar Códigos',
    'codes.exportCodes': 'Exportar Códigos',
    'codes.addPromoCode': 'Añadir Código Promocional',
    'codes.addRedeemCode': 'Añadir Código de Canje',
    'codes.codeLabel': 'Código',
    'codes.enterCodePlaceholder': 'Ingrese código de canje...',
    'codes.importTitle': 'Importar Códigos de Canje',
    'codes.importHelpText': 'Sube un archivo Excel o CSV con códigos de canje. La primera columna debe contener los códigos alfanuméricos.',
    'codes.exportTitle': 'Exportar Códigos de Canje',
    'codes.exportSelectedCodes': 'Exportar códigos seleccionados',
    'codes.exportAllCodesFor': 'Exportar todos los códigos para',
    'codes.withQrCodes': 'con sus códigos QR.',
    'codes.downloadQRCode': 'Descargar Código QR',
    'codes.deleteCode': 'Eliminar Código',
    'codes.errorImportFile': 'Error al importar el archivo. Por favor verifica el formato.',
    'codes.errorDeleteCode': 'Error al eliminar el código',
    'codes.fetchingRedeemCodes': 'Obteniendo datos de códigos de canje...',
    'codes.redeemCodesPageSubtitle': 'Gestionar códigos de canje y códigos QR',
    
    // Banners
    'banners.title': 'Gestión de Banners',
    'banners.add': 'Añadir Banner',
    'banners.edit': 'Editar Banner',
    'banners.delete': 'Eliminar Banner',
    'banners.confirmDelete': 'Está seguro de que desea eliminar este banner?',
    'banners.name': 'Nombre',
    'banners.image': 'Imagen',
    'banners.url': 'URL',
    'banners.startDate': 'Fecha de Inicio',
    'banners.endDate': 'Fecha de Fin',
    'banners.active': 'Activo',
    'banners.inactive': 'Inactivo',
    'banners.preview': 'Vista Previa',
    'banners.search': 'Buscar banners...',
    'banners.filter': 'Filtrar',
    'banners.status': 'Estado',
    'banners.allStatuses': 'Todos los Estados',
    'banners.previous': 'Anterior',
    'banners.next': 'Siguiente',
    'app.close': 'Cerrar',
    
    // Reports
    'reports.title': 'Informes y Estadísticas',
    'reports.newUsers': 'Nuevos Usuarios',
    'reports.sales': 'Ventas',
    'reports.userActivity': 'Actividad de Usuarios',
    'reports.export': 'Exportar',
    'reports.exportConfirmation': 'Los informes se exportarán en formato CSV',
    'reports.period': 'Período',
    'reports.daily': 'Diario',
    'reports.weekly': 'Semanal',
    'reports.monthly': 'Mensual',
    'reports.yearly': 'Anual',
    'reports.fromLastMonth': 'desde el mes pasado',
    'reports.recentActivity': 'Actividad Reciente',
    'app.action': 'Acción',
    'app.details': 'Detalles',
    'app.actionCannotBeUndone': 'Esta acción no se puede deshacer',
    
    // Notifications
    'notifications.title': 'Notificaciones Push',
    'notifications.compose': 'Redactar',
    'notifications.target': 'Objetivo',
    'notifications.global': 'Global',
    'notifications.specific': 'Usuarios Específicos',
    'notifications.preview': 'Vista Previa',
    'notifications.send': 'Enviar',
    'notifications.history': 'Historial',
    'notifications.message': 'Mensaje',
    'notifications.title_field': 'Título',
    'notifications.body': 'Contenido',
    'notifications.status': 'Estado',
    'notifications.sent': 'Enviada',
    'notifications.scheduled': 'Programada',
    'notifications.confirmSend': 'Estás seguro de que quieres enviar esta notificación?',
    'notifications.success': 'Notificación enviada con éxito',
    'notifications.selectUsers': 'Seleccionar Usuarios',
    'notifications.searchUsers': 'Buscar usuarios',
    'notifications.selectedUsers': 'Usuarios Seleccionados',
    'notifications.date': 'Fecha',
    'notifications.time': 'Hora',
    'notifications.scheduleFor': 'Programar para',
    'notifications.country': 'País',
    'notifications.state': 'Estado',
    'notifications.city': 'Ciudad',
    'notifications.loadingUsers': 'Cargando usuarios...',
    'notifications.noUsersFound': 'No se encontraron usuarios',

    // Settings
    'settings.title': 'Configuración',
    'settings.general': 'General',
    'settings.profile': 'Perfil',
    'settings.security': 'Seguridad',
    'settings.generalSettings': 'Configuración General',
    'settings.profileSettings': 'Configuración del Perfil',
    'settings.securitySettings': 'Configuración de Seguridad',
    'settings.language': 'Idioma',
    'settings.languageDescription': 'Elige tu idioma preferido para la interfaz',
    'settings.theme': 'Tema',
    'settings.themeDescription': 'Elige entre tema claro y oscuro',
    'settings.lightTheme': 'Claro',
    'settings.darkTheme': 'Oscuro',
    'settings.savePreferences': 'Guardar Preferencias',
    'settings.saveSuccess': 'Configuración guardada exitosamente',
    'settings.changesDetected': 'Cambios detectados - la configuración se aplicará inmediatamente',
    'settings.name': 'Nombre',
    'settings.email': 'Correo Electrónico',
    'settings.phone': 'Teléfono',
    'settings.currentPassword': 'Contraseña Actual',
    'settings.newPassword': 'Nueva Contraseña',
    'settings.confirmPassword': 'Confirmar Contraseña',
    'settings.updatePassword': 'Actualizar Contraseña',
    'settings.saveProfile': 'Guardar Perfil',
    'settings.defaultName': 'Usuario Administrador',
    'settings.defaultEmail': 'admin@ejemplo.com',
    'settings.defaultPhone': '+1 (555) 123-4567',
    'settings.currentPasswordRequired': 'La contraseña actual es requerida',
    'settings.newPasswordRequired': 'La nueva contraseña es requerida',
    'settings.passwordMinLength': 'La contraseña debe tener al menos 8 caracteres',
    'settings.confirmPasswordRequired': 'Por favor confirme su contraseña',
    'settings.passwordsDoNotMatch': 'Las contraseñas no coinciden',
    'settings.passwordUpdateSuccess': 'Contraseña actualizada exitosamente',
    'settings.profileUpdateSuccess': 'Perfil actualizado exitosamente',

    // Additional
    'app.date': 'Fecha',
    'users.loggedIn': 'Inició sesión',
    'users.deleteConfirmTitle': 'Confirmar eliminación',
    'users.deleteSuccess': 'Usuario eliminado con éxito!',
    'users.deleteFailed': 'Error al eliminar usuario',
    'users.deleteError': 'Se produjo un error al eliminar el usuario',
    'admins.emailStatus': 'Estado del correo',
    'admins.verified': 'Verificado',
    'admins.pendingVerification': 'Verificación pendiente',
    'admins.sendEmail': 'Enviar correo',
    'admins.resetPassword.title': 'Enviar correo de restablecimiento de contraseña',
    'admins.resetPassword.message': '¿Estás seguro de que deseas enviar un correo de restablecimiento de contraseña?',
    'admins.cancel': 'Cancelar',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: () => '',
});

export const useLanguage = () => useContext(LanguageContext);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Load language preference from localStorage if available
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'es')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  const t = (key: string): string => {
    const translation = translations[language] as Record<string, string>;
    return translation[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
